#ifndef TOFNENTITY_H_
#define TOFNENTITY_H_

enum
{

    ENTTYPE_NONE = 0x00,
    ENTTYPE_PLAYER = 0x01,
    ENTTYPE_ENEMY = 0x02,
    ENTTYPE_ENBULLET = 0x04,
    ENTTYPE_PLYBULLET = 0x08,
    ENTTYPE_POWERUP = 0x10,
    ENTTYPE_EXPLOSION = 0x20,

};

#endif
